"""
Pydantic схемы для API.
"""
from src.schemas.telegram_auth import (
    TelegramAuthRequest,
    TelegramAuthResponse,
    TelegramLinkRequest,
    TelegramLinkResponse,
    TelegramUnlinkResponse,
    TelegramAuthError,
    UserResponse,
)
from src.schemas.analytics import (
    ListenerStatsResponse,
    ListenerHistoryPoint,
    ListenerHistoryResponse,
    TopTrackItem,
    TopTracksResponse,
    AnalyticsSummaryResponse,
    TrackPlayRequest,
    TrackPlayResponse,
)
from src.schemas.notifications import (
    NotificationChannelBase,
    NotificationChannelCreate,
    NotificationChannelUpdate,
    NotificationChannelResponse,
    NotificationTemplateBase,
    NotificationTemplateCreate,
    NotificationTemplateUpdate,
    NotificationTemplateResponse,
    NotificationRecipientBase,
    NotificationRecipientCreate,
    NotificationRecipientUpdate,
    NotificationRecipientResponse,
    NotificationRuleBase,
    NotificationRuleCreate,
    NotificationRuleUpdate,
    NotificationRuleResponse,
    DeliveryLogResponse,
)

__all__ = [
    "TelegramAuthRequest",
    "TelegramAuthResponse",
    "TelegramLinkRequest",
    "TelegramLinkResponse",
    "TelegramUnlinkResponse",
    "TelegramAuthError",
    "UserResponse",
    # Analytics schemas
    "ListenerStatsResponse",
    "ListenerHistoryPoint",
    "ListenerHistoryResponse",
    "TopTrackItem",
    "TopTracksResponse",
    "AnalyticsSummaryResponse",
    "TrackPlayRequest",
    "TrackPlayResponse",
    # Notifications schemas
    "NotificationChannelBase",
    "NotificationChannelCreate",
    "NotificationChannelUpdate",
    "NotificationChannelResponse",
    "NotificationTemplateBase",
    "NotificationTemplateCreate",
    "NotificationTemplateUpdate",
    "NotificationTemplateResponse",
    "NotificationRecipientBase",
    "NotificationRecipientCreate",
    "NotificationRecipientUpdate",
    "NotificationRecipientResponse",
    "NotificationRuleBase",
    "NotificationRuleCreate",
    "NotificationRuleUpdate",
    "NotificationRuleResponse",
    "DeliveryLogResponse",
]
