{{- if and .Values.frontend.enabled .Values.frontend.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sattva-streamer.frontend.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sattva-streamer.frontend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $secret := .Values.frontend.secretEnv }}
  {{ $key }}: {{ $secret | b64enc | quote }}
  {{- end }}
{{- end }}
