openapi: 3.0.3
info:
  title: System Monitoring API
  description: |
    API для мониторинга системных метрик и событий активности.
    Часть фичи 015-real-system-monitoring.
  version: 1.0.0

servers:
  - url: /api/system
    description: Backend API

paths:
  /metrics:
    get:
      summary: Получить текущие системные метрики
      description: |
        Возвращает актуальные метрики системы: CPU, RAM, диск, латентность, 
        соединения к БД. Данные собираются в реальном времени через psutil.
      operationId: getSystemMetrics
      tags:
        - Metrics
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Успешный ответ с метриками
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemMetrics'
              example:
                cpu_percent: 45.2
                ram_percent: 62.8
                disk_percent: 35.1
                latency_ms: 12.5
                db_connections: 5
                db_max_connections: 100
                timestamp: "2025-11-30T12:00:00Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '503':
          description: Метрики временно недоступны
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Не удалось получить метрики системы"

  /activity:
    get:
      summary: Получить список событий активности
      description: |
        Возвращает последние события системы: регистрации, одобрения,
        действия с трансляцией, изменения плейлиста.
      operationId: getActivityEvents
      tags:
        - Activity
      security:
        - bearerAuth: []
      parameters:
        - name: limit
          in: query
          description: Максимальное количество событий
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Смещение для пагинации
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: type
          in: query
          description: Фильтр по типу события
          required: false
          schema:
            $ref: '#/components/schemas/ActivityEventType'
      responses:
        '200':
          description: Успешный ответ со списком событий
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityEventsResponse'
              example:
                events:
                  - id: 1
                    type: "user_registered"
                    message: "Новый пользователь зарегистрировался"
                    user_email: "user@example.com"
                    created_at: "2025-11-30T11:55:00Z"
                  - id: 2
                    type: "stream_started"
                    message: "Трансляция запущена"
                    created_at: "2025-11-30T11:30:00Z"
                total: 42
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SystemMetrics:
      type: object
      required:
        - cpu_percent
        - ram_percent
        - disk_percent
        - latency_ms
        - db_connections
        - db_max_connections
        - timestamp
      properties:
        cpu_percent:
          type: number
          format: float
          minimum: 0
          maximum: 100
          description: Загрузка CPU в процентах
        ram_percent:
          type: number
          format: float
          minimum: 0
          maximum: 100
          description: Использование RAM в процентах
        disk_percent:
          type: number
          format: float
          minimum: 0
          maximum: 100
          description: Использование диска в процентах
        latency_ms:
          type: number
          format: float
          minimum: 0
          description: Задержка ответа API в миллисекундах
        db_connections:
          type: integer
          minimum: 0
          description: Текущее количество соединений к БД
        db_max_connections:
          type: integer
          minimum: 1
          description: Максимальное количество соединений к БД
        timestamp:
          type: string
          format: date-time
          description: Время измерения в UTC

    ActivityEventType:
      type: string
      enum:
        - user_registered
        - user_approved
        - user_rejected
        - stream_started
        - stream_stopped
        - stream_error
        - track_added
        - track_removed
        - system_warning
        - system_error
      description: Тип события активности

    ActivityEvent:
      type: object
      required:
        - id
        - type
        - message
        - created_at
      properties:
        id:
          type: integer
          description: Уникальный идентификатор события
        type:
          $ref: '#/components/schemas/ActivityEventType'
        message:
          type: string
          description: Читаемое описание события
        user_email:
          type: string
          format: email
          nullable: true
          description: Email связанного пользователя
        details:
          type: object
          additionalProperties: true
          nullable: true
          description: Дополнительные данные события
        created_at:
          type: string
          format: date-time
          description: Время создания события в UTC

    ActivityEventsResponse:
      type: object
      required:
        - events
        - total
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/ActivityEvent'
        total:
          type: integer
          description: Общее количество событий (для пагинации)

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Описание ошибки

  responses:
    Unauthorized:
      description: Не авторизован
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Not authenticated"

    Forbidden:
      description: Доступ запрещён
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Not authorized to access this resource"

tags:
  - name: Metrics
    description: Системные метрики (CPU, RAM, диск, латентность)
  - name: Activity
    description: Лента событий активности системы
