"""add_telegram_auth_and_channels

Revision ID: 3ca9c3980420
Revises: c7f9a88e3b2
Create Date: 2025-11-27 12:32:22.283184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.database


# revision identifiers, used by Alembic.
revision: str = '3ca9c3980420'
down_revision: Union[str, None] = 'c7f9a88e3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_accounts',
    sa.Column('id', src.database.GUID(), nullable=False),
    sa.Column('user_id', src.database.GUID(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('encrypted_session', sa.String(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channels',
    sa.Column('id', src.database.GUID(), nullable=False),
    sa.Column('account_id', src.database.GUID(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ffmpeg_args', sa.String(), nullable=True),
    sa.Column('video_quality', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['telegram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_items',
    sa.Column('id', src.database.GUID(), nullable=False),
    sa.Column('channel_id', src.database.GUID(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_by', src.database.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_table('playlist_items')
    op.drop_table('channels')
    op.drop_table('telegram_accounts')
    # ### end Alembic commands ###
