"""Create recovery_logs table

Revision ID: a1b2c3d4e5f6
Revises: m1n2o3p4q5r6
Create Date: 2025-12-23 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import src.database

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'm1n2o3p4q5r6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create ENUM types
    recovery_failure_type = sa.Enum('network', 'api_rate_limit', 'codec_error', 'session_expired', 'process_crash', 'unknown', name='recovery_failure_type')
    recovery_failure_type.create(op.get_bind(), checkfirst=True)

    recovery_strategy = sa.Enum('restart', 'reconnect', 'fallback', 'manual', name='recovery_strategy')
    recovery_strategy.create(op.get_bind(), checkfirst=True)

    recovery_status = sa.Enum('pending', 'in_progress', 'success', 'failed', 'abandoned', name='recovery_status')
    recovery_status.create(op.get_bind(), checkfirst=True)

    # Create recovery_logs table
    op.create_table('recovery_logs',
    sa.Column('id', src.database.GUID(), nullable=False),
    sa.Column('stream_id', src.database.GUID(), nullable=False),

    # Failure Information
    sa.Column('failure_type', sa.Enum('network', 'api_rate_limit', 'codec_error', 'session_expired', 'process_crash', 'unknown', name='recovery_failure_type', create_type=False), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),

    # Recovery Configuration
    sa.Column('recovery_strategy', sa.Enum('restart', 'reconnect', 'fallback', 'manual', name='recovery_strategy', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'success', 'failed', 'abandoned', name='recovery_status', create_type=False), nullable=False),

    # Retry Tracking
    sa.Column('attempt_number', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('max_attempts', sa.Integer(), nullable=False, server_default='3'),
    sa.Column('backoff_seconds', sa.Integer(), nullable=True),

    # Timestamps
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),

    # Additional Context (JSONB)
    sa.Column('error_details', postgresql.JSONB(), nullable=True),
    sa.Column('recovery_metadata', postgresql.JSONB(), nullable=True),
    sa.Column('circuit_breaker_state', postgresql.JSONB(), nullable=True),

    # Foreign Key and Primary Key
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Create indexes
    op.create_index(op.f('ix_recovery_logs_stream_id'), 'recovery_logs', ['stream_id'], unique=False)
    op.create_index(op.f('ix_recovery_logs_failure_type'), 'recovery_logs', ['failure_type'], unique=False)
    op.create_index(op.f('ix_recovery_logs_status'), 'recovery_logs', ['status'], unique=False)
    op.create_index(op.f('ix_recovery_logs_started_at'), 'recovery_logs', ['started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_logs_started_at'), table_name='recovery_logs')
    op.drop_index(op.f('ix_recovery_logs_status'), table_name='recovery_logs')
    op.drop_index(op.f('ix_recovery_logs_failure_type'), table_name='recovery_logs')
    op.drop_index(op.f('ix_recovery_logs_stream_id'), table_name='recovery_logs')
    op.drop_table('recovery_logs')

    # Drop ENUM types
    sa.Enum(name='recovery_failure_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='recovery_strategy').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='recovery_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
