"""Add multi-platform streaming models

Revision ID: a1b2c3d4e5f6
Revises: n1o2p3q4r5s6
Create Date: 2026-01-23 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from src.database import GUID


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'n1o2p3q4r5s6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create streaming_platforms table
    op.create_table('streaming_platforms',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('platform_type', sa.String(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('encrypted_credentials', sa.Text(), nullable=True),
    sa.Column('stream_key', sa.String(), nullable=True),
    sa.Column('stream_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streaming_platforms_user_id'), 'streaming_platforms', ['user_id'], unique=False)

    # Create broadcast_destinations table
    op.create_table('broadcast_destinations',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('platform_id', GUID(), nullable=False),
    sa.Column('platform_settings', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('custom_title', sa.String(), nullable=True),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['streaming_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_destinations_channel_id'), 'broadcast_destinations', ['channel_id'], unique=False)
    op.create_index(op.f('ix_broadcast_destinations_platform_id'), 'broadcast_destinations', ['platform_id'], unique=False)

    # Create social_media_posts table
    op.create_table('social_media_posts',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('platform_id', GUID(), nullable=False),
    sa.Column('post_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('platform_post_id', sa.String(length=255), nullable=True),
    sa.Column('platform_post_url', sa.String(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.BigInteger(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['streaming_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_media_posts_channel_id'), 'social_media_posts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_social_media_posts_channel_status'), 'social_media_posts', ['channel_id', 'status'], unique=False)
    op.create_index(op.f('ix_social_media_posts_platform_id'), 'social_media_posts', ['platform_id'], unique=False)
    op.create_index(op.f('ix_social_media_posts_status'), 'social_media_posts', ['status'], unique=False)

    # Create chat_messages table
    op.create_table('chat_messages',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('platform_id', GUID(), nullable=False),
    sa.Column('channel_id', GUID(), nullable=False),
    sa.Column('platform_message_id', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_display_name', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('author_color', sa.String(length=7), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['streaming_platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_platform_channel', 'chat_messages', ['platform_id', 'channel_id'], unique=False)
    op.create_index('idx_chat_messages_platform_message_id', 'chat_messages', ['platform_id', 'platform_message_id'], unique=False)
    op.create_index('idx_chat_messages_timestamp', 'chat_messages', ['message_timestamp'], unique=False)
    op.create_index(op.f('ix_chat_messages_channel_id'), 'chat_messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_platform_id'), 'chat_messages', ['platform_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_platform_message_id'), 'chat_messages', ['platform_message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop chat_messages table
    op.drop_index(op.f('ix_chat_messages_platform_message_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_platform_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_channel_id'), table_name='chat_messages')
    op.drop_index('idx_chat_messages_timestamp', table_name='chat_messages')
    op.drop_index('idx_chat_messages_platform_message_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_platform_channel', table_name='chat_messages')
    op.drop_table('chat_messages')

    # Drop social_media_posts table
    op.drop_index(op.f('ix_social_media_posts_status'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_platform_id'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_channel_status'), table_name='social_media_posts')
    op.drop_index(op.f('ix_social_media_posts_channel_id'), table_name='social_media_posts')
    op.drop_table('social_media_posts')

    # Drop broadcast_destinations table
    op.drop_index(op.f('ix_broadcast_destinations_platform_id'), table_name='broadcast_destinations')
    op.drop_index(op.f('ix_broadcast_destinations_channel_id'), table_name='broadcast_destinations')
    op.drop_table('broadcast_destinations')

    # Drop streaming_platforms table
    op.drop_index(op.f('ix_streaming_platforms_user_id'), table_name='streaming_platforms')
    op.drop_table('streaming_platforms')

    # ### end Alembic commands ###
