"""add session health fields

Revision ID: o1p2q3r4s5t6
Revises: n1o2p3q4r5s6
Create Date: 2026-01-24 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'o1p2q3r4s5t6'
down_revision: Union[str, None] = 'n1o2p3q4r5s6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_accounts', sa.Column('session_health_status', sa.String(), nullable=True))
    op.add_column('telegram_accounts', sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True))
    op.add_column('telegram_accounts', sa.Column('session_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('telegram_accounts', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('telegram_accounts', sa.Column('auto_refresh_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('telegram_accounts', sa.Column('refresh_before_expires_hours', sa.Integer(), server_default=sa.text('24'), nullable=False))
    op.add_column('telegram_accounts', sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('telegram_accounts', sa.Column('refresh_error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_accounts', 'refresh_error_message')
    op.drop_column('telegram_accounts', 'last_refreshed_at')
    op.drop_column('telegram_accounts', 'refresh_before_expires_hours')
    op.drop_column('telegram_accounts', 'auto_refresh_enabled')
    op.drop_column('telegram_accounts', 'totp_secret')
    op.drop_column('telegram_accounts', 'session_expires_at')
    op.drop_column('telegram_accounts', 'last_health_check')
    op.drop_column('telegram_accounts', 'session_health_status')
    # ### end Alembic commands ###
