"""add rotation order field

Revision ID: p1q2r3s4t5u6
Revises: o1p2q3r4s5t6
Create Date: 2026-01-24 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'p1q2r3s4t5u6'
down_revision: Union[str, None] = 'o1p2q3r4s5t6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add rotation_order field for multi-account load balancing
    op.add_column('telegram_accounts', sa.Column('rotation_order', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # Create index on rotation_order for efficient selection queries
    op.create_index('ix_telegram_accounts_rotation_order', 'telegram_accounts', ['rotation_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telegram_accounts_rotation_order', table_name='telegram_accounts')
    op.drop_column('telegram_accounts', 'rotation_order')
    # ### end Alembic commands ###
