"""Add webhooks and webhook_events tables

Revision ID: p3q4r5s6t7u8
Revises: o2p3q4r5s6t7
Create Date: 2026-01-23 12:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import src.database

# revision identifiers, used by Alembic.
revision: str = 'p3q4r5s6t7u8'
down_revision: Union[str, None] = 'o2p3q4r5s6t7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create webhooks table
    op.create_table('webhooks',
    sa.Column('id', src.database.GUID(), nullable=False),
    sa.Column('owner_id', src.database.GUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('event_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_owner_id'), 'webhooks', ['owner_id'], unique=False)

    # Create webhook_events table
    op.create_table('webhook_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('webhook_id', src.database.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'),
    sa.Column('attempt_number', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('should_retry', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_events_webhook_id', 'webhook_events', ['webhook_id'], unique=False)
    op.create_index('idx_webhook_events_event_type', 'webhook_events', ['event_type'], unique=False)
    op.create_index('idx_webhook_events_status', 'webhook_events', ['status'], unique=False)
    op.create_index('idx_webhook_events_attempted_at', 'webhook_events', ['attempted_at'], unique=False)
    op.create_index('idx_webhook_events_event_id', 'webhook_events', ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop webhook_events table and indexes
    op.drop_index('idx_webhook_events_event_id', table_name='webhook_events')
    op.drop_index('idx_webhook_events_attempted_at', table_name='webhook_events')
    op.drop_index('idx_webhook_events_status', table_name='webhook_events')
    op.drop_index('idx_webhook_events_event_type', table_name='webhook_events')
    op.drop_index('idx_webhook_events_webhook_id', table_name='webhook_events')
    op.drop_table('webhook_events')

    # Drop webhooks table and indexes
    op.drop_index(op.f('ix_webhooks_owner_id'), table_name='webhooks')
    op.drop_table('webhooks')

    # ### end Alembic commands ###
