{{- if .Values.streamer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sattva-streamer.streamer.serviceName" . }}-secrets
  labels:
    {{- include "sattva-streamer.streamer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.telegramApiId }}
  telegram-api-id: {{ .Values.secrets.telegramApiId | b64enc | quote }}
  {{- else }}
  telegram-api-id: {{ required "A valid Telegram API ID is required" .Values.streamer.secretEnv.API_ID | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.telegramApiHash }}
  telegram-api-hash: {{ .Values.secrets.telegramApiHash | b64enc | quote }}
  {{- else }}
  telegram-api-hash: {{ required "A valid Telegram API Hash is required" .Values.streamer.secretEnv.API_HASH | b64enc | quote }}
  {{- end }}
{{- end }}
