{{- if and .Values.redis.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sattva-streamer.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
    release: prometheus-operator
  {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaces:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    path: /metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
    scheme: http
  {{- with .Values.monitoring.serviceMonitor.relabelings }}
  relabelings:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.monitoring.serviceMonitor.metricRelabelings }}
  metricRelabelings:
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
